# .bashrc

for f in /etc/bashrc ~/.bashrc.local; do
	[[ -r $f ]] && . $f
done

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
PYTHONPATH=/home/akrherz/projects/pyLDM/src:/home/akrherz/projects/pyIEM/src:/home/akrherz/projects/nwnserver:/home/akrherz/projects/twitty-twister:/opt/rtstats/pylib:/home/akrherz/projects/iembot/src:/home/akrherz/projects/pyVBCam/src:/home/akrherz/projects/python-metar:/home/akrherz/projects/MetPy/src:/home/akrherz/projects/tilecache/src:/home/akrherz/projects/pyWWA/parsers:/home/akrherz/projects/iem-web-services/src
export PYTHONPATH

PATH=$PATH:$HOME/.local/bin:$HOME/bin:/opt/gradle-6.0.1/bin:$HOME/install4j7/bin:/opt/maven/bin:/home/meteor_ldm/bin
export PATH

. /opt/intel/oneapi/setvars.sh >& /dev/null

SVN_EDITOR=vi
export SVN_EDITOR

# https://coderwall.com/p/fasnya/add-git-branch-name-to-bash-prompt
parse_git_branch() {
     git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}
PROMPT_DIRTRIM=2
export PS1="\h \[\033[32m\]\w\[\033[33m\]\$(parse_git_branch)\[\033[00m\] $ "


if [ -f /opt/miniconda3/bin/activate ]; then
        . /opt/miniconda3/etc/profile.d/conda.sh
        conda activate prod
fi

alias javaws='/opt/jre1.8.0_231/bin/javaws'
alias vpnui='/opt/cisco/anyconnect/bin/vpnui'
alias inkscape="flatpak run org.inkscape.Inkscape"
