#
# Begin ~/.bash_profile
#
# Jason White <jdwhite@menelos.com>
#
# When bash is invoked as an interactive login shell, or as a 
# non-interactive shell with the --login option, it first reads
# and executes commands from the file /etc/profile, if that file
# exists.
#
# After reading that file, it looks for ~/.bash_profile,
# ~/.bash_login, and ~/.profile, in that order, and reads and
# executes commands from the first one that exists and is readable.
# The --noprofile option may be used when the shell is started to
# inhibit this behavior.
#
# Everything goes in ~/.bashrc. It's trivial to test for interactive/login
# shells within a single file and act accordingly rather than deal with the
# inherent annoyances of using both ~/.bash_profile and ~/.bashrc and not
# having them sourced when expected. -jdwhite
#
[[ -r ~/.bashrc ]] && . ~/.bashrc

# User specific environment and startup programs

