# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs

PATH=/opt/miniconda2/bin:$PATH:$HOME/.local/bin:$HOME/bin:/opt/gradle/bin
export PATH
