# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
PYTHONPATH=/home/akrherz/projects/pyLDM/:/home/akrherz/projects/pyIEM:/home/akrherz/projects/nwnserver:/home/akrherz/projects/twitty-twister:/opt/rtstats/pylib:/home/akrherz/projects/iembot/:/home/akrherz/projects/pyVBCam/:/home/akrherz/projects/python-metar
export PYTHONPATH

PATH=/home/akrherz/bin:$PATH
export PATH

SVN_EDITOR=vi
export SVN_EDITOR

# https://coderwall.com/p/fasnya/add-git-branch-name-to-bash-prompt
parse_git_branch() {
     git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}
PROMPT_DIRTRIM=2
export PS1="\h \[\033[32m\]\w\[\033[33m\]\$(parse_git_branch)\[\033[00m\] $ "

alias javaws="/usr/lib/jvm/jre-1.8.0_oracle/bin/javaws"
