<html>
<head>
<meta HTTP-EQUIV=CONTENT-TYPE CONTENT="text/html; charset=utf-8">
<title>Slide 1</title>
</head>
<body text="black" bgcolor="white" link=#000080 vlink=#800000 alink=#000080>

<table bgcolor="#EEEEEE">
<tr><td>
This presentation was made for the Iowa State Atmospheric Science Seminar
Series on 14 October 2003.

<p>This presentation was made with <a href="http://www.openoffice.org">OpenOffice.org</a>, the presentation can be
downloaded  <a href="present.sxi">here</a>.  The presentation has been 
converted to <a href="present.pdf">PDF</a> and <a href="present.swf">Flash</a> formats.
</td></tr></table>

</body>
</html>
