<?php
require_once "/opt/iem/config/settings.inc.php";
require_once "/opt/iem/include/myview.php";

$t = new MyView();
$t->title = "Presentations";
$t->thispage = "iem-present";

$t->content = <<<EOF
<h3>Presentation Archive</h3>

<div class="row">
<div class="col-md-3 col-sm-3 well">
<img src="/~akrherz/images/sandiego066.jpg" class="img img-responsive" />
</div>
<div class="col-md93 col-sm-9">
<p>We have been honored to present our work on a number of occasions across the United States.  Here is a listing of presentations and the electronic materials used during the talks.  If there is an IEM talk you attended and not found on this list, please let us know. 

<p>Click the date in the table to view materials used during the presentation.
</div>
</div>

<table class="table table-striped">
<thead>
<tr>
 <th>Date</th><th>Event</th><th>Location</th>
</tr>
</thead>

<tbody>
<tr><td><a href="/present/200922_soo/">2020 Sep 22</a></td><td>NWS Central Region SE SOO Virtual Conference
<br /><strong>Title:</strong> The IEM and other things that should interest the audience.</td><td>Webex</td></tr>

<tr><td><a href="/present/200220_dmx/">2020 Feb 20</a></td><td>NWS Des Moines
<br /><strong>Title:</strong> The Weather Bureau &amp; The IEM: The Best of Friends!!!</td><td>Johnston, IA</td></tr>

<tr><td><a href="/present/200205_agron600b/">2020 Feb 5</a></td><td>Agronomy 600B Seminar
<br /><strong>Title:</strong> Providing the E in G x E x M</td><td>Ames, IA</td></tr>

<tr><td><a href="/present/190402_crops/">2019 Apr 2</a></td><td>ISU ANR Crops In-Service
<br /><strong>Title:</strong> Mesonet Refresher</td><td>Ames, IA</td></tr>

<tr><td><a href="/present/190320_pub/">2019 Mar 20</a></td><td>NWS Pueblo
<br /><strong>Title:</strong> IEM Dog and Pony Show</td><td>Pueblo, CO</td></tr>

<tr><td><a href="/present/180918_eax/">2018 Sep 18</a></td><td>NWS Pleasant Hill
<br /><strong>Title:</strong> IEM Dog and Pony Show</td><td>Pleasant Hill, MO</td></tr>

<tr><td><a href="/present/180912_top/">2018 Sep 12</a></td><td>NWS Topeka
<br /><strong>Title:</strong> IEM Dog and Pony Show</td><td>Topeka, KS</td></tr>

<tr><td><a href="/present/180403_lbf/">2018 Apr 3</a></td><td>NWS North Platte
<br /><strong>Title:</strong> IEM Dog and Pony Show</td><td>North Platte, NE</td></tr>

<tr><td><a href="/present/180301_seiara/">2018 Mar 1</a></td><td>Southeast Iowa Agricultural Research Association
<br /><strong>Title:</strong> Utilizing Weather Station Data to Improve Crop Management</td><td>Iowa City, IA</td></tr>

<tr><td><a href="/present/180227_bigdata/">2018 Feb 27</a></td><td>Big Data for (Sm)all Farmers Workshop
<br /><strong>Title:</strong> Big Weather Data for (sm)all Farmers</td><td>Ames, IA</td></tr>

<tr><td><a href="/present/180221_interop/">2018 Feb 21</a></td><td>Emergency Interoperability Consortium
<br /><strong>Title:</strong> NWS Valid Time Event Code (VTEC)</td><td>Virtual</td></tr>

<tr><td><a href="/present/171012_eod/">2017 Oct 12</a></td><td>ISU GIS Earth Observation Day
<br /><strong>Title:</strong> IEM + GIS + Other Acronyms</td><td>Ames, IA</td></tr>

<tr><td><a href="/present/170916_nws/">2017 Sep 16</a></td><td>NWS Des Moines Open-House
<br /><strong>Title:</strong> Iowa Environmental Mesonet (IEM): Making Weather Data Great Again</td><td>Johnston, IA</td></tr>

<tr><td><a href="/present/160926_unidata/">2016 Sep 26</a></td><td>Unidata DeSouza Award Presentation
<br /><strong>Title:</strong> 2016 Russell L. DeSouza Award</td><td>Boulder, CO</td></tr>

<tr><td><a href="/present/160912_ag590/">2016 Sep 12</a></td><td>ISU Agronomy 590RD
<br /><strong>Title:</strong> The Case for Relational Databases (make databases great again!)</td><td>Ames, IA</td></tr>

<tr><td><a href="/present/160525_ind/">2016 May 25</a></td><td>Indianapolis NWS
<br /><strong>Title:</strong> IEM Dog and Pony Show</td><td>Indianapolis, IN</td></tr>

<tr><td><a href="/present/150916_crops/">2015 Sep 16</a></td><td>ISU Crops Team In-Service
<br /><strong>Title:</strong> Using the Mesonet</td><td>Ames, IA</td></tr>

<tr><td><a href="/present/150330_crops/">2015 Mar 30</a></td><td>ISU Crops Team In-Service
<br /><strong>Title:</strong> Using the Mesonet</td><td>Ames, IA</td></tr>

<tr><td><a href="/present/141110_lot/">2014 Nov 10</a></td><td>Chicago NWS
<br /><strong>Title:</strong> IEM Dog and Pony Show</td><td>Chicago, IL</td></tr>

<tr><td><a href="/present/140304_mpx/">2014 Mar 4</a></td><td>Minneapolis NWS
<br /><strong>Title:</strong> IEM Dog and Pony Show</td><td>Minneapolis, MN</td></tr>

<tr><td><a href="/present/130903_isu/">2013 Sep 3</a></td><td>ISU Geology/Meteorology Seminar
<br /><strong>Title:</strong> How much did it rain in Ames on 25 June 2010?</td><td>Ames, IA</td></tr>

<tr><td><a href="/present/130302_psci/">2013 Mar 2</a></td><td>Professional Soil Classifiers of Iowa
<br /><strong>Title:</strong> On the 2012 Drought and other items of interest</td><td>Ames, IA</td></tr>

<tr><td><a href="/present/120412_oax/">2012 Apr 12</a></td><td>Omaha NWS Severe Weather Workshop
<br /><strong>Title:</strong> Musings on Storm Based Warnings</td><td>Omaha, NE</td></tr>

<tr><td><a href="/present/110401_nwa/">2011 Apr 1</a></td><td>Central Iowa NWA Conference
<br /><strong>Title:</strong> The illusion of Storm Based Warnings</td><td>Ankeny, IA</td></tr>

<tr><td><a href="/present/090922_isu/">2009 Sep 22</a></td><td>ISU Meteorology Seminar
<br /><strong>Title:</strong> IEM Potpourri (combine a bunch of unrelated stuff and see if it smells good at the end)</td><td>Ames, IA</td></tr>

<tr><td><a href="/present/080327_nwa/">2008 Mar 27</a></td><td>Central Iowa NWA Conference
<br /><strong>Title:</strong> Webcam Shock &amp; Awe</td><td>Des Moines, IA</td></tr>

<tr><td><a href="/present/080228_uni/">2008 Feb 28</a></td><td>UNI - GeoTREE Seminar
<br /><strong>Title:</strong> Iowa Environmental Mesonet: Using Open Source GIS Tools and Web Services to Disseminate Environmental Data</td><td>Cedar Falls, IA</td></tr>

<tr><td><a href="/present/071219_extension/">2007 Dec 19</a></td><td>Experiment Farm Meeting
<br /><strong>Title:</strong> Iowa Environmental Mesonet</td><td>Ames, IA</td></tr>

<tr><td><a href="/present/071127_isu/">2007 Nov 27</a></td><td>ISU Meteorology Seminar
<br /><strong>Title:</strong> Iowa Environmental Mesonet: “Where’s the Science?”</td><td>Ames, IA</td></tr>

<tr><td><a href="/present/071107_wisc/">2007 Nov 7</a></td><td>U of Wisconsin GIS Day
<br /><strong>Title:</strong> Iowa Environmental Mesonet: Using Open Source GIS Tools and Web Services to Disseminate Environmental Data</td><td>Madison, WI</td></tr>

<tr><td><a href="/present/070324_nwa/">2007 Mar 24</a></td><td>Central Iowa NWA Conference
<br /><strong>Title:</strong> Iowa Environmental Mesonet: Supporting the real-time and research needs of the national severe weather community</td><td>Des Moines, IA</td></tr>

<tr><td><a href="/present/070214_crh/">2007 Feb 14</a></td><td>NWS Central Region SOO/WCM Conference
<br /><strong>Title:</strong> IEM Chat and other things that should interest the audience</td><td>Kansas City, MO</td></tr>

<tr><td><a href="/present/061205_polygon/">2006 Dec 5</a></td><td>NWS Storm Based Warnings Workshop
<br /><strong>Title:</strong> NWS VTEC/Polygon Stuff</td><td>College Station, TX</td></tr>

<tr><td><a href="/present/061114_asa/">2006 Nov 14</a></td><td>Agronomy Society Annual Meeting
<br /><strong>Title:</strong> 166-7: Modeling Out Crossing Probabilities for Maize in Iowa</td><td>Indianapolis, IN</td></tr>

<tr><td><a href="/present/061010_isu/">2006 Oct 10</a></td><td>ISU Meteorology Seminar
<br /><strong>Title:</strong> IEM Update: From pollen to rivers to pavements to soils and a whole lot more</td><td>Ames, IA</td></tr>

<tr><td><a href="/present/060907_agron/">2006 Sep 7</a></td><td>Agronomy 600 Seminar
<br /><strong>Title:</strong> Coupling Lagrangian Stochastics and Large Eddy Simulation to Predict Long Distance Dispersal of Pollen</td><td>Ames, IA</td></tr>

<tr><td>2006 May 10</td><td>West Elementary Career Fair
<br /><strong>Title:</strong> --</td><td>Polk City, IA</td></tr>

<tr><td>2006 Apr 28</td><td>Postville Elementary Career Fair
<br /><strong>Title:</strong> --</td><td>Postville, IA</td></tr>

<tr><td>2006 Apr 3</td><td>SchoolNet8 Training
<br /><strong>Title:</strong> --</td><td>Polk City, IA</td></tr>

<tr><td>2006 Mar 28</td><td>SchoolNet8 Training
<br /><strong>Title:</strong> --</td><td>Fort Dodge, IA</td></tr>

<tr><td><a href="/present/060325_nwa">2006 Mar 25</a></td><td>Central Iowa NWA
<br /><strong>Title:</strong> IEM Chat: A New Platform for Building NWS and Media Partnerships</td><td>Des Moines, IA</td></tr>

<tr><td>2006 Mar 9</td><td>SchoolNet8 Training
<br /><strong>Title:</strong> KCCI SchoolNet8 Workshop</td><td>Des Moines, IA</td></tr>

<tr><td><a href="/present/060120_hun">2006 Jan 20</a></td><td>NWS Huntsville Presentation
<br /><strong>Title:</strong> Iowa Environmental Mesonet: IEMChat and other tools for the NWS</td><td>Huntsville, AL</td></tr>

<tr><td><a href="/present/060120_baron">2006 Jan 20</a></td><td>Baron Services Training Conference
<br /><strong>Title:</strong> Cyclone Saturday, An Examination of the Teamwork and Technology used on  12 November 2005</td><td>Huntsville, AL</td></tr>

<tr><td><a href="/present/051016_nwa">2005 Oct 16</a></td><td>National Weather Association Annual Meeting
<br /><strong>Title:</strong> Why can’t we all get along? A New Template for Public-Private Cooperation.</td><td>St Louis, MO</td></tr>

<tr><td><a href="/present/050827_baron">2005 Aug 27</a></td><td>Baron Services Training Conference
<br /><strong>Title:</strong> Now you can really see the weather!</td><td>Huntsville, AL</td></tr>

<tr><td><a href="/present/050420_nasa">2005 Apr 20</a></td><td>Iowa-NASA Data Integration Workshop
<br /><strong>Title:</strong> Using Open GIS web services to serve environmental data</td><td>Ames, IA</td></tr>

<tr><td><a href="/present/050405_cipco">2005 Apr 05</a></td><td>KCCI SchoolNet Training Inservice
<br /><strong>Title:</strong> KCCI SchoolNet8 Workshop</td><td>Des Moines, IA</td></tr>

<tr><td><a href="/present/050112_ams/">2005 Jan 12</a></td><td>American Meteorological Society Annual Meeting
<br /><strong>Title:</strong> 12.3 Using Open GIS web services to  serve environmental data</td><td>San Diego, CA</td></tr>

<tr><td><a href="/present/040918_baron">2004 Sep 18</a></td><td>Baron Services Training Conference
<br /><strong>Title:</strong> Mayhem in May, How Baron Tools Saved the Day: 21 &amp; 22 May 2004</td><td>Huntsville, AL</td></tr>

<tr><td><a href="/present/040318_lse">2004 Mar 18</a></td><td>NWS LaCrosse Presentation
<br /><strong>Title:</strong> The Iowa Environment Mesonet</td><td>LaCrosse, WI</td></tr>

<tr><td><a href="/present/040227_dvn">2004 Feb 27</a></td><td>NWS Davenport Presentation
<br /><strong>Title:</strong> The Iowa Environment Mesonet</td><td>Davenport, IA</td></tr>

<tr><td><a href="/present/040224_cipco">2004 Feb 24</a></td><td>KCCI SchoolNet Training Inservice
<br /><strong>Title:</strong> KCCI SchoolNet8 Workshop</td><td>Des Moines, IA</td></tr>

<tr><td><a href="/present/040115_ams">2004 Jan 15</a></td><td>American Meteorological Society Annual Meeting
<br /><strong>Title:</strong> Serving NEXRAD imagery with Open-Source GIS</td><td>Seattle, WA</td></tr>

<tr><td><a href="/present/031121_fsd">2003 Nov 21</a></td><td>NWS Sioux Falls Presentation
<br /><strong>Title:</strong> The Iowa Environmental Mesonet</td><td>Sioux Falls, IA</td></tr>

<tr><td><a href="/present/031105_asa">2003 Nov 05</a></td><td>American Society of Agronomy Annual Meeting
<br /><strong>Title:</strong> Implementing Weather and Climate Data Networks for Agriculture</td><td>Denver, IA</td></tr>

<tr><td><a href="/present/031022_igic">2003 Oct 22</a></td><td>Iowa Geographic Information Council Quarterly meeting (video conference)
<br /><strong>Title:</strong> IEM Access &amp; Free GIS</td><td>Ames, IA</td></tr>

<tr><td><a href="/present/031014_isu">2003 Oct 14</a></td><td>Iowa State Meteorology Department Seminar
<br /><strong>Title:</strong> IEM: Shock &amp; Awe</td><td>Ames, IA</td></tr>

<tr><td><a href="/present/030926_baron">2003 Sep 26</a></td><td>Baron Services Training Conference
<br /><strong>Title:</strong> Utilizing your School Network</td><td>Huntsville, AL</td></tr>

<tr><td><a href="/present/030917_nevada">2003 Sep 17</a></td><td>SchoolNet training workshop
<br /><strong>Title:</strong> KCCI SchoolNet8 and the Iowa Mesonet</td><td>Nevada, IA</td></tr>

<tr><td><a href="/present/030701_igic">2003 Jul 01</a></td><td>Iowa Geographic Information Council Annual Meeting
<br /><strong>Title:</strong> Open Source GIS for Iowa Environmental Mesonet Data</td><td>Ames, IA</td></tr>

<tr><td><a href="/present/030625_unidata">2003 Jun 25</a></td><td>UNIDATA Expanding Horizons Conference
<br /><strong>Title:</strong> Using Non-Traditional Observational Networks: The Iowa Environmental mesonet</td><td>Boulder, CO</td></tr>

<tr><td><a href="/present/030514_epa">2003 May 14</a></td><td>EPA Environmental Monitoring Conference
<br /><strong>Title:</strong> Building the Iowa Environmental Mesonet</td><td>Kansas City, MO</td></tr>

<tr><td><a href="/present/030218_cipco">2003 Feb 18</a></td><td>KCCI SchoolNet Training Inservice
<br /><strong>Title:</strong> KCCI SchoolNet8 and the Iowa Mesonet</td><td>Des Moines, IA</td></tr>

<tr><td><a href="/present/030211_ams">2003 Feb 11</a></td><td>American Meteorological Society Annual Meeting
<br /><strong>Title:</strong> Using GIS for Environmental Data in Iowa</td><td>Long Beach, CA</td></tr>

<tr><td><a href="/present/021120_marshall">2002 Nov 20</a></td><td>Marshall County GIS Day
<br /><strong>Title:</strong> The Iowa Environmental Mesonet - KCCI SchoolNet - National Weather Service  Partnership</td><td>Ames, IA</td></tr>

<tr><td><a href="/present/021120_isugis">2002 Nov 20</a></td><td>Iowa State GIS Day
<br /><strong>Title:</strong> The IEM-KCCI-NWS Partnership: Working Together to Save Lives and Increase Weather Data Distribution</td><td>Ames, IA</td></tr>

<tr><td><a href="/present/021021_nwa">2002 Oct 21</a></td><td>National Weather Association Annual Meeting
<br /><strong>Title:</strong> The IEM-KCCI-NWS Partnership: Working Together to Save Lives and Increase Weather Data Distribution</td><td>Fort Worth, TX</td></tr>

<tr><td><a href="/present/020924_isu">2002 Sep 24</a></td><td>Iowa State Meteorology Department Seminar
<br /><strong>Title:</strong> Iowa Environmental Mesonet: Past, Present, &amp; Future</td><td>Ames, IA</td></tr>

<tr><td><a href="/present/020825_barons">2002 Aug 25</a></td><td>Baron Services Training Conference
<br /><strong>Title:</strong> The IEM-KCCI-NWS Partnership: Working Together to Save Lives and Increase Weather Data Distribution</td><td>Huntsville, AL</td></tr>

<tr><td><a href="/present/020812_ncar">2002 Aug 12</a></td><td>NCAR GIS Conference
<br /><strong>Title:</strong> Serving Iowa Mesonet data with U of Minnesota's MapServer</td><td>Boulder, CO</td></tr>

<tr><td><a href="/present/020626_suth">2002 Jun 26</a></td><td>ISU Experiment Farm Day
<br /><strong>Title:</strong> Iowa Environmental Mesonet</td><td>Sutherland, IA</td></tr>

<tr><td><a href="/present/020405_oax">2002 Apr 05</a></td><td>NWS Omaha presentation
<br /><strong>Title:</strong> Iowa Environmental Mesonet</td><td>Omaha, NE</td></tr>

<tr><td><a href="/present/020322_CInwa">2002 Mar 22</a></td><td>Central Iowa NWA Severe Storms Conference
<br /><strong>Title:</strong> Iowa Environmental Mesonet</td><td>Des Moines, IA</td></tr>

<tr><td><a href="/present/011004_isu">2001 Oct 04</a></td><td>Iowa State Meteorology Department Seminar
<br /><strong>Title:</strong> Iowa Environmental Mesonet</td><td>Ames, IA</td></tr> 

</tbody>
</table>
EOF;
$t->render('single.phtml');
?>
